# Generated by Django 5.0.4 on 2024-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coment',
            new_name='content',
        ),
    ]
