# Generated by Django 5.0.4 on 2024-05-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
