# Generated by Django 5.0.4 on 2024-05-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_post_id_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
    ]
